# Generated by Django 5.2.1 on 2025-05-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='demo_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='software',
            name='download_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='software',
            name='features',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='software',
            name='requirements',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='software',
            name='screenshots',
            field=models.JSONField(default=list),
        ),
    ]
